# Generated by Django 4.1.2 on 2024-06-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Suscriptor',
        ),
    ]
